// AIH Safe Base Scaffold — foundational contract only. Do not add feature logic here.

// Typed audit event kinds for all AIH Safe governance actions.
// Emitted by lib/aihsafe/audit/ and written to ActivityLog (existing) or a dedicated table (Phase 2+).
export const AuditEventKind = {
  // Family Unit lifecycle
  FAMILY_UNIT_CREATED:   "family_unit.created",
  FAMILY_UNIT_DISSOLVED: "family_unit.dissolved",

  // Guardian relationship
  GUARDIAN_LINKED:        "guardian.linked",
  GUARDIAN_UNLINKED:      "guardian.unlinked",
  GUARDIAN_CONSENT_GIVEN: "guardian.consent_given",
  GUARDIAN_CONSENT_DENIED:"guardian.consent_denied",

  // Child profile
  CHILD_PROFILE_CREATED:   "child_profile.created",
  CHILD_PROFILE_SUSPENDED: "child_profile.suspended",

  // Invite (AIH Safe paths)
  INVITE_SENT_CHILD:         "invite.sent_child",
  INVITE_GUARDIAN_APPROVED:  "invite.guardian_approved",
  INVITE_GUARDIAN_DECLINED:  "invite.guardian_declined",

  // Visibility
  VISIBILITY_CHANGED: "visibility.changed",

  // Membership
  MEMBERSHIP_GRANTED: "membership.granted",
  MEMBERSHIP_REVOKED: "membership.revoked",

  // Trust
  TRUST_UNIT_FORMED:      "trust_unit.formed",
  TRUST_UNIT_MEMBER_ADDED:"trust_unit.member_added",

  // Founder settings
  FOUNDER_SETTINGS_UPDATED: "founder_settings.updated",

  // Limits engine (Agent 41)
  LIMIT_REACHED: "limits.reached",
} as const;
export type AuditEventKind = (typeof AuditEventKind)[keyof typeof AuditEventKind];

// Minimal audit event envelope. No DB shape — that is defined by the audit service.
export interface AuditEventEnvelope {
  id:        string;          // generated by audit service
  kind:      AuditEventKind;
  actorId:   string;          // UserId of the user who triggered the action
  targetId:  string | null;   // UserId, FamilyUnitId, etc. depending on kind
  createdAt: string;          // ISO 8601
  meta:      Record<string, unknown>;
}
