// lib/discovery/catalog.ts
// Hardcoded subject catalog for the AIH Discovery Channel.
// No database required — starter data, curated by hand.

import type { Subject } from "./types";

// ─── 1. Science Lab ───────────────────────────────────────────────────────────

const SCIENCE: Subject = {
  id: "science",
  slug: "science",
  title: "Science Lab",
  subhead: "Experiments, space, biology, chemistry, physics, weather, and the mysteries of the universe.",
  heroSubhead: "Explore the universe through experiments, physics, chemistry, weather, biology, and discovery. Every investigation is curated and safe to explore at your own pace.",
  icon: "🔬",
  accentColor: "#22c55e",
  thumbGradient: "linear-gradient(135deg, #1e3a5f 0%, #2563eb 60%, #4338ca 100%)",
  subtopics: [
    { id: "physics", label: "Physics" },
    { id: "chemistry", label: "Chemistry" },
    { id: "space", label: "Space" },
    { id: "biology", label: "Biology" },
    { id: "weather", label: "Weather" },
    { id: "earth-science", label: "Earth Science" },
  ],
  featuredItems: [
    {
      id: "sci-f1",
      title: "The Quantum World",
      description: "Step inside the strange rules of quantum mechanics — particles, waves, and why observation changes everything.",
      ageTier: "9-12",
      itemType: "Investigation",
      thumbGradient: "linear-gradient(135deg, #312e81 0%, #6366f1 100%)",
      duration: "18 min",
    },
    {
      id: "sci-f2",
      title: "Photosynthesis: Life's Engine",
      description: "How plants turn sunlight into sugar — the most important chemical reaction on Earth, explained step by step.",
      ageTier: "6-8",
      itemType: "Mini-Doc",
      thumbGradient: "linear-gradient(135deg, #14532d 0%, #16a34a 100%)",
      duration: "14 min",
    },
    {
      id: "sci-f3",
      title: "Kitchen Chemistry Lab",
      description: "Five safe experiments you can run right now with ingredients already in your kitchen.",
      ageTier: "3-5",
      itemType: "Workshop",
      thumbGradient: "linear-gradient(135deg, #713f12 0%, #f59e0b 100%)",
      duration: "30 min",
      episodes: 5,
    },
    {
      id: "sci-f4",
      title: "The Mystery of Dark Matter",
      description: "Scientists know it exists — they just cannot see it. Explore the invisible 85% of the universe.",
      ageTier: "9-12",
      itemType: "Investigation",
      thumbGradient: "linear-gradient(135deg, #0c0a09 0%, #475569 100%)",
      duration: "22 min",
    },
    {
      id: "sci-f5",
      title: "Why Is Weather Unpredictable?",
      description: "Chaos theory, pressure systems, and the butterfly effect — why the forecast is always uncertain.",
      ageTier: "6-8",
      itemType: "Interactive",
      thumbGradient: "linear-gradient(135deg, #1e3a5f 0%, #93c5fd 100%)",
      duration: "20 min",
    },
  ],
  projects: [
    {
      id: "sci-p1",
      title: "Build a Barometer",
      description: "Measure air pressure changes with a jar, a balloon, and a straw — then predict rain before it arrives.",
      ageTier: "K-2",
      itemType: "Project",
      thumbGradient: "linear-gradient(135deg, #1e3a5f 0%, #7dd3fc 100%)",
      duration: "45 min",
      difficulty: "Easy",
      buildTime: "45 min",
    },
    {
      id: "sci-p2",
      title: "Vinegar Rocket Launch",
      description: "Baking soda + vinegar + a plastic bottle = real propulsion. Measure altitude and calculate force.",
      ageTier: "3-5",
      itemType: "Project",
      thumbGradient: "linear-gradient(135deg, #7f1d1d 0%, #ef4444 100%)",
      duration: "1 hr",
      difficulty: "Intermediate",
      buildTime: "1 hour",
    },
    {
      id: "sci-p3",
      title: "DIY Water Filtration",
      description: "Layer gravel, sand, and charcoal to filter dirty water, then test the results. Real environmental engineering.",
      ageTier: "6-8",
      itemType: "Project",
      thumbGradient: "linear-gradient(135deg, #042f2e 0%, #14b8a6 100%)",
      duration: "2 hrs",
      difficulty: "Advanced",
      buildTime: "2 hours",
    },
  ],
  trails: [
    {
      id: "sci-t1",
      title: "Atoms to Reactions",
      description: "Start with the smallest building blocks and work your way up to the reactions that power the world.",
      steps: ["Atoms", "Elements", "Molecules", "Compounds", "Reactions", "Products"],
      ageTier: "3-5",
      itemCount: 6,
      thumbGradient: "linear-gradient(135deg, #14532d 0%, #4ade80 100%)",
    },
    {
      id: "sci-t2",
      title: "Space Exploration Path",
      description: "From our solar system to the edge of the observable universe — a guided journey through everything we know.",
      steps: ["Solar System", "Stars", "Galaxies", "Black Holes", "Universe", "Beyond?"],
      ageTier: "6-8",
      itemCount: 6,
      thumbGradient: "linear-gradient(135deg, #0c0a09 0%, #6366f1 100%)",
    },
  ],
};

// ─── 2. Math Zone ─────────────────────────────────────────────────────────────

const MATH: Subject = {
  id: "math",
  slug: "math",
  title: "Math Zone",
  subhead: "Patterns, puzzles, numbers, geometry, logic, and real-world problem solving.",
  heroSubhead: "Discover the hidden math in everything around you — from nature's spirals to the algorithms in your phone. Problems are just puzzles waiting to be unlocked.",
  icon: "📐",
  accentColor: "#f59e0b",
  thumbGradient: "linear-gradient(135deg, #451a03 0%, #d97706 60%, #fbbf24 100%)",
  subtopics: [
    { id: "mental-math", label: "Mental Math" },
    { id: "geometry", label: "Geometry" },
    { id: "algebra", label: "Algebra" },
    { id: "logic", label: "Logic" },
    { id: "probability", label: "Probability" },
    { id: "math-games", label: "Math Games" },
  ],
  featuredItems: [
    {
      id: "mth-f1",
      title: "Prime Numbers: The Ultimate Mystery",
      description: "Why are primes distributed the way they are? Mathematicians have chased this for 2,000 years.",
      ageTier: "9-12",
      itemType: "Investigation",
      thumbGradient: "linear-gradient(135deg, #1c1917 0%, #d97706 100%)",
      duration: "16 min",
    },
    {
      id: "mth-f2",
      title: "Geometry in Nature",
      description: "Honeycombs, shells, snowflakes, and spirals — why does nature keep using the same shapes?",
      ageTier: "6-8",
      itemType: "Mini-Doc",
      thumbGradient: "linear-gradient(135deg, #14532d 0%, #fbbf24 100%)",
      duration: "14 min",
    },
    {
      id: "mth-f3",
      title: "Mental Math Superpowers",
      description: "Five techniques to multiply, divide, and estimate faster in your head than on a calculator.",
      ageTier: "3-5",
      itemType: "Interactive",
      thumbGradient: "linear-gradient(135deg, #7c3aed 0%, #fbbf24 100%)",
      duration: "25 min",
    },
    {
      id: "mth-f4",
      title: "What Are the Odds?",
      description: "Probability from coin flips to birthday paradoxes — why our intuition about chance is usually wrong.",
      ageTier: "6-8",
      itemType: "Investigation",
      thumbGradient: "linear-gradient(135deg, #0c4a6e 0%, #f59e0b 100%)",
      duration: "18 min",
    },
    {
      id: "mth-f5",
      title: "Graph Theory and the Internet",
      description: "Seven bridges of Königsberg to GPS routing — how one math idea became the backbone of the web.",
      ageTier: "9-12",
      itemType: "Investigation",
      thumbGradient: "linear-gradient(135deg, #1e1b4b 0%, #fbbf24 100%)",
      duration: "20 min",
    },
  ],
  projects: [
    {
      id: "mth-p1",
      title: "Fibonacci Spiral Art",
      description: "Draw the golden ratio spiral using a compass and ruler — then find it in 10 places around you.",
      ageTier: "K-2",
      itemType: "Project",
      thumbGradient: "linear-gradient(135deg, #713f12 0%, #fbbf24 100%)",
      duration: "30 min",
      difficulty: "Easy",
      buildTime: "30 min",
    },
    {
      id: "mth-p2",
      title: "Class Statistics Survey",
      description: "Design a real survey, collect data, and build charts that reveal something surprising about your group.",
      ageTier: "3-5",
      itemType: "Project",
      thumbGradient: "linear-gradient(135deg, #1e3a5f 0%, #f59e0b 100%)",
      duration: "1.5 hrs",
      difficulty: "Intermediate",
      buildTime: "1.5 hours",
    },
    {
      id: "mth-p3",
      title: "Logic Puzzle Design",
      description: "Create your own logic grid puzzle for others to solve — test it, refine it, then swap with someone.",
      ageTier: "6-8",
      itemType: "Project",
      thumbGradient: "linear-gradient(135deg, #312e81 0%, #fbbf24 100%)",
      duration: "2 hrs",
      difficulty: "Advanced",
      buildTime: "2 hours",
    },
  ],
  trails: [
    {
      id: "mth-t1",
      title: "Numbers to Algebra",
      description: "Follow the natural progression from counting all the way to variables and equations.",
      steps: ["Counting", "Fractions", "Decimals", "Algebra", "Functions", "Calculus"],
      ageTier: "K-2",
      itemCount: 6,
      thumbGradient: "linear-gradient(135deg, #451a03 0%, #fbbf24 100%)",
    },
    {
      id: "mth-t2",
      title: "Logic to Mathematical Proof",
      description: "How mathematicians prove things with absolute certainty — starting from basic logic.",
      steps: ["Logic", "Statements", "Deduction", "Proof"],
      ageTier: "9-12",
      itemCount: 4,
      thumbGradient: "linear-gradient(135deg, #1e1b4b 0%, #f59e0b 100%)",
    },
  ],
};

// ─── 3. Code & Computers ──────────────────────────────────────────────────────

const CODE: Subject = {
  id: "code-computers",
  slug: "code-computers",
  title: "Code & Computers",
  subhead: "Programming, AI, cybersecurity, game building, hardware, and how computers think.",
  heroSubhead: "Learn how the digital world actually works — from the logic gates in your CPU to the neural networks behind AI. Then build something real.",
  icon: "💻",
  accentColor: "#6366f1",
  thumbGradient: "linear-gradient(135deg, #1e1b4b 0%, #4f46e5 60%, #06b6d4 100%)",
  subtopics: [
    { id: "python", label: "Python" },
    { id: "ai-basics", label: "AI Basics" },
    { id: "game-dev", label: "Game Dev" },
    { id: "cyber-safety", label: "Cyber Safety" },
    { id: "hardware", label: "Hardware" },
    { id: "internet-basics", label: "Internet Basics" },
  ],
  featuredItems: [
    {
      id: "cod-f1",
      title: "How Your Phone Recognizes Faces",
      description: "The neural network that unlocks your phone — convolutional layers, training data, and what can go wrong.",
      ageTier: "All Ages",
      itemType: "Investigation",
      thumbGradient: "linear-gradient(135deg, #1e1b4b 0%, #ec4899 100%)",
      duration: "16 min",
    },
    {
      id: "cod-f2",
      title: "Build a Chatbot in 30 Minutes",
      description: "Follow along to create a rule-based chatbot using Python — no AI required. Real code, real output.",
      ageTier: "6-8",
      itemType: "Workshop",
      thumbGradient: "linear-gradient(135deg, #042f2e 0%, #14b8a6 100%)",
      duration: "35 min",
    },
    {
      id: "cod-f3",
      title: "Cybersecurity: Protect Your Data",
      description: "How hackers think — password cracking, phishing, and the real steps to staying safe online.",
      ageTier: "9-12",
      itemType: "Investigation",
      thumbGradient: "linear-gradient(135deg, #450a0a 0%, #ef4444 100%)",
      duration: "22 min",
    },
    {
      id: "cod-f4",
      title: "How the Internet Works",
      description: "DNS, TCP/IP, HTTP — follow a cat photo from a server in Tokyo to your screen in under 100ms.",
      ageTier: "All Ages",
      itemType: "Mini-Doc",
      thumbGradient: "linear-gradient(135deg, #0c4a6e 0%, #0ea5e9 100%)",
      duration: "16 min",
    },
    {
      id: "cod-f5",
      title: "Game Dev: Make a Platformer",
      description: "Collision detection, gravity, scoring — build a working jump-and-run in Python with Pygame.",
      ageTier: "9-12",
      itemType: "Workshop",
      thumbGradient: "linear-gradient(135deg, #3b0764 0%, #7c3aed 100%)",
      duration: "45 min",
      episodes: 3,
    },
  ],
  projects: [
    {
      id: "cod-p1",
      title: "Scratch Catch Game",
      description: "A falling-objects catch game in Scratch — sprites, timers, and scoring, start to finish.",
      ageTier: "3-5",
      itemType: "Project",
      thumbGradient: "linear-gradient(135deg, #1e1b4b 0%, #818cf8 100%)",
      duration: "30 min",
      difficulty: "Easy",
      buildTime: "30 min",
    },
    {
      id: "cod-p2",
      title: "Python CLI Calculator",
      description: "Build a command-line calculator with history, error handling, and at least one secret feature.",
      ageTier: "6-8",
      itemType: "Project",
      thumbGradient: "linear-gradient(135deg, #042f2e 0%, #22d3ee 100%)",
      duration: "1 hr",
      difficulty: "Intermediate",
      buildTime: "1 hour",
    },
    {
      id: "cod-p3",
      title: "Build Your First Website",
      description: "HTML, CSS, and one line of JavaScript — a personal page that actually lives on the web.",
      ageTier: "9-12",
      itemType: "Project",
      thumbGradient: "linear-gradient(135deg, #1e1b4b 0%, #6366f1 100%)",
      duration: "3 hrs",
      difficulty: "Advanced",
      buildTime: "3 hours",
    },
  ],
  trails: [
    {
      id: "cod-t1",
      title: "Logic to Programs",
      description: "Trace the journey from boolean logic all the way to writing programs that solve real problems.",
      steps: ["Logic", "Variables", "Loops", "Functions", "Programs"],
      ageTier: "6-8",
      itemCount: 5,
      thumbGradient: "linear-gradient(135deg, #1e1b4b 0%, #22d3ee 100%)",
    },
    {
      id: "cod-t2",
      title: "Data Science Path",
      description: "From raw data to insight — statistics, visualization, and machine learning fundamentals.",
      steps: ["Data", "Statistics", "Visualization", "Models", "Insight"],
      ageTier: "9-12",
      itemCount: 5,
      thumbGradient: "linear-gradient(135deg, #042f2e 0%, #a855f7 100%)",
    },
  ],
};

// ─── 4. Build & Engineering ───────────────────────────────────────────────────

const ENGINEERING: Subject = {
  id: "engineering",
  slug: "engineering",
  title: "Build & Engineering",
  subhead: "Robotics, circuits, bridges, machines, drones, fabrication, and invention.",
  heroSubhead: "Engineering is thinking made physical. Design under constraints, build, test, fail, improve. The best engineers never stop tinkering.",
  icon: "⚙️",
  accentColor: "#f97316",
  thumbGradient: "linear-gradient(135deg, #431407 0%, #ea580c 60%, #fbbf24 100%)",
  subtopics: [
    { id: "robotics", label: "Robotics" },
    { id: "electronics", label: "Electronics" },
    { id: "3d-printing", label: "3D Printing" },
    { id: "machines", label: "Machines" },
    { id: "flight", label: "Flight" },
    { id: "structures", label: "Structures" },
  ],
  featuredItems: [
    {
      id: "eng-f1",
      title: "Why Bridges Don't Fall Down",
      description: "Compression, tension, and triangles — the geometry of structural strength explained with real bridges.",
      ageTier: "3-5",
      itemType: "Investigation",
      thumbGradient: "linear-gradient(135deg, #1c1917 0%, #78716c 100%)",
      duration: "14 min",
    },
    {
      id: "eng-f2",
      title: "Electronics for Beginners",
      description: "Breadboards, resistors, and LEDs — wire your first working circuit and understand every component.",
      ageTier: "6-8",
      itemType: "Workshop",
      thumbGradient: "linear-gradient(135deg, #052e16 0%, #84cc16 100%)",
      duration: "40 min",
      episodes: 4,
    },
    {
      id: "eng-f3",
      title: "How Rockets Reach Space",
      description: "Newton's third law, Tsiolkovsky's equation, staging — the physics of escaping Earth's gravity.",
      ageTier: "9-12",
      itemType: "Investigation",
      thumbGradient: "linear-gradient(135deg, #0c0a09 0%, #0ea5e9 100%)",
      duration: "22 min",
    },
    {
      id: "eng-f4",
      title: "The Physics of Flight",
      description: "Lift, drag, thrust, weight — Bernoulli and Newton both explain why planes fly, just differently.",
      ageTier: "6-8",
      itemType: "Mini-Doc",
      thumbGradient: "linear-gradient(135deg, #1e3a5f 0%, #7dd3fc 100%)",
      duration: "18 min",
    },
    {
      id: "eng-f5",
      title: "3D Printing: From Idea to Object",
      description: "Slicing, supports, infill density — every decision that turns a digital model into a physical object.",
      ageTier: "9-12",
      itemType: "Interactive",
      thumbGradient: "linear-gradient(135deg, #3b0764 0%, #f97316 100%)",
      duration: "28 min",
    },
  ],
  projects: [
    {
      id: "eng-p1",
      title: "Toothpick Bridge Challenge",
      description: "Design a toothpick bridge to hold the maximum weight — then test it to destruction.",
      ageTier: "3-5",
      itemType: "Project",
      thumbGradient: "linear-gradient(135deg, #713f12 0%, #f97316 100%)",
      duration: "1 hr",
      difficulty: "Easy",
      buildTime: "1 hour",
    },
    {
      id: "eng-p2",
      title: "LED Mood Circuit",
      description: "Wire a breadboard circuit with LEDs, a potentiometer, and a switch — controlled by you.",
      ageTier: "6-8",
      itemType: "Project",
      thumbGradient: "linear-gradient(135deg, #052e16 0%, #22c55e 100%)",
      duration: "1.5 hrs",
      difficulty: "Intermediate",
      buildTime: "1.5 hours",
    },
    {
      id: "eng-p3",
      title: "Servo Motor Robot Arm",
      description: "Program a 3-axis servo arm with an Arduino to pick up small objects — then teach it a sequence.",
      ageTier: "9-12",
      itemType: "Project",
      thumbGradient: "linear-gradient(135deg, #1e1b4b 0%, #f97316 100%)",
      duration: "4 hrs",
      difficulty: "Advanced",
      buildTime: "4 hours",
    },
  ],
  trails: [
    {
      id: "eng-t1",
      title: "Simple Machines to Robots",
      description: "From levers and pulleys to motor-driven machines — every robot is built on simple principles.",
      steps: ["Levers", "Pulleys", "Gears", "Motors", "Sensors", "Robots"],
      ageTier: "3-5",
      itemCount: 6,
      thumbGradient: "linear-gradient(135deg, #431407 0%, #f97316 100%)",
    },
    {
      id: "eng-t2",
      title: "Electricity to Electronics",
      description: "From static sparks to programmable circuits — the complete beginner journey through electronics.",
      steps: ["Electricity", "Circuits", "Components", "Breadboards", "Microcontrollers", "Projects"],
      ageTier: "6-8",
      itemCount: 6,
      thumbGradient: "linear-gradient(135deg, #052e16 0%, #84cc16 100%)",
    },
  ],
};

// ─── 5. Nature & Earth ────────────────────────────────────────────────────────

const NATURE: Subject = {
  id: "nature-earth",
  slug: "nature-earth",
  title: "Nature & Earth",
  subhead: "Animals, oceans, geology, storms, ecosystems, farming, and the living planet.",
  heroSubhead: "Earth is the most complex system we know of. Oceans, weather, ecosystems, and geology are all interconnected — and still full of mystery.",
  icon: "🌿",
  accentColor: "#16a34a",
  thumbGradient: "linear-gradient(135deg, #052e16 0%, #16a34a 60%, #a3e635 100%)",
  subtopics: [
    { id: "animals", label: "Animals" },
    { id: "oceans", label: "Oceans" },
    { id: "weather", label: "Weather" },
    { id: "geology", label: "Geology" },
    { id: "farming", label: "Farming" },
    { id: "ecology", label: "Ecology" },
  ],
  featuredItems: [
    {
      id: "nat-f1",
      title: "A Day in a Rainforest",
      description: "Four layers, thousands of species, and a system so complex it produces its own weather.",
      ageTier: "K-2",
      itemType: "Mini-Doc",
      thumbGradient: "linear-gradient(135deg, #052e16 0%, #4ade80 100%)",
      duration: "12 min",
    },
    {
      id: "nat-f2",
      title: "Ocean Trenches: The Last Unknown",
      description: "We have mapped more of Mars than our own ocean floor. Here is what lives 11km down.",
      ageTier: "9-12",
      itemType: "Investigation",
      thumbGradient: "linear-gradient(135deg, #082f49 0%, #0284c7 100%)",
      duration: "24 min",
    },
    {
      id: "nat-f3",
      title: "How Volcanoes Form",
      description: "Tectonic plates, magma chambers, and the slow violence happening under your feet right now.",
      ageTier: "6-8",
      itemType: "Interactive",
      thumbGradient: "linear-gradient(135deg, #7f1d1d 0%, #ef4444 100%)",
      duration: "20 min",
    },
    {
      id: "nat-f4",
      title: "Rewilding: Returning What We Took",
      description: "What happens when wolves return to Yellowstone, or beavers return to British rivers? Everything changes.",
      ageTier: "All Ages",
      itemType: "Mini-Doc",
      thumbGradient: "linear-gradient(135deg, #14532d 0%, #a3e635 100%)",
      duration: "18 min",
    },
    {
      id: "nat-f5",
      title: "The Secret Life of Soil",
      description: "One teaspoon of healthy soil contains more organisms than there are humans on Earth. Here is why that matters.",
      ageTier: "6-8",
      itemType: "Investigation",
      thumbGradient: "linear-gradient(135deg, #292524 0%, #a8a29e 100%)",
      duration: "16 min",
    },
  ],
  projects: [
    {
      id: "nat-p1",
      title: "Grow a Microgreen Garden",
      description: "Seeds, soil, light, water — grow your first edible plants from start to plate in two weeks.",
      ageTier: "K-2",
      itemType: "Project",
      thumbGradient: "linear-gradient(135deg, #052e16 0%, #86efac 100%)",
      duration: "14 days",
      difficulty: "Easy",
      buildTime: "Ongoing (14 days)",
    },
    {
      id: "nat-p2",
      title: "Backyard Compost Bin",
      description: "Build a working compost system from cardboard and kitchen scraps — and understand why it heats up.",
      ageTier: "3-5",
      itemType: "Project",
      thumbGradient: "linear-gradient(135deg, #292524 0%, #a3e635 100%)",
      duration: "1 hr",
      difficulty: "Intermediate",
      buildTime: "1 hour build + 6 weeks observation",
    },
    {
      id: "nat-p3",
      title: "Rain Collection & Measurement",
      description: "Build a rain gauge, collect data for a month, and compare it to the official weather station nearby.",
      ageTier: "6-8",
      itemType: "Project",
      thumbGradient: "linear-gradient(135deg, #1e3a5f 0%, #4ade80 100%)",
      duration: "1 hr",
      difficulty: "Advanced",
      buildTime: "1 hour + ongoing data collection",
    },
  ],
  trails: [
    {
      id: "nat-t1",
      title: "From Soil to Table",
      description: "Trace the complete journey food takes from microbes in the soil to a meal on your plate.",
      steps: ["Soil Microbes", "Plants", "Pollinators", "Harvest", "Nutrition", "Food Systems"],
      ageTier: "3-5",
      itemCount: 6,
      thumbGradient: "linear-gradient(135deg, #052e16 0%, #fbbf24 100%)",
    },
    {
      id: "nat-t2",
      title: "Ocean Life Explorer",
      description: "Dive from the sunlit surface to the crushing depths and meet the creatures in each zone.",
      steps: ["Sunlit Zone", "Twilight Zone", "Midnight Zone", "Abyssal Zone"],
      ageTier: "6-8",
      itemCount: 4,
      thumbGradient: "linear-gradient(135deg, #082f49 0%, #22d3ee 100%)",
    },
  ],
};

// ─── 6. History & Civilization ────────────────────────────────────────────────

const HISTORY: Subject = {
  id: "history",
  slug: "history",
  title: "History & Civilization",
  subhead: "Ancient worlds, inventions, exploration, architecture, archaeology, and the story of humanity.",
  heroSubhead: "Every civilization left clues. Archaeology, written records, and careful reasoning let us reconstruct worlds that vanished thousands of years ago. Let's explore them.",
  icon: "🏛️",
  accentColor: "#d97706",
  thumbGradient: "linear-gradient(135deg, #292524 0%, #92400e 60%, #d97706 100%)",
  subtopics: [
    { id: "ancient-civ", label: "Ancient Civilizations" },
    { id: "explorers", label: "Explorers" },
    { id: "architecture", label: "Architecture" },
    { id: "archaeology", label: "Archaeology" },
    { id: "inventions", label: "Inventions" },
    { id: "world-history", label: "World History" },
  ],
  featuredItems: [
    {
      id: "his-f1",
      title: "The Silk Road: 8,000 Miles of Trade",
      description: "Before the internet, ideas, spices, diseases, and entire religions traveled this ancient network of routes.",
      ageTier: "6-8",
      itemType: "Mini-Doc",
      thumbGradient: "linear-gradient(135deg, #7c2d12 0%, #f59e0b 100%)",
      duration: "20 min",
    },
    {
      id: "his-f2",
      title: "Ancient Egypt Beyond the Pyramids",
      description: "Medicine, law, taxation, poetry — the full civilization that most documentaries skip.",
      ageTier: "3-5",
      itemType: "Investigation",
      thumbGradient: "linear-gradient(135deg, #713f12 0%, #fde68a 100%)",
      duration: "18 min",
    },
    {
      id: "his-f3",
      title: "The Industrial Revolution Changed Everything",
      description: "Steam, coal, factories, and child labor — how 1760–1840 created the modern world and its problems.",
      ageTier: "9-12",
      itemType: "Investigation",
      thumbGradient: "linear-gradient(135deg, #1c1917 0%, #78716c 100%)",
      duration: "22 min",
    },
    {
      id: "his-f4",
      title: "Lost Cities Rediscovered",
      description: "Pompeii, Machu Picchu, Angkor Wat, Great Zimbabwe — how archaeologists find cities history forgot.",
      ageTier: "All Ages",
      itemType: "Mini-Doc",
      thumbGradient: "linear-gradient(135deg, #292524 0%, #d4a373 100%)",
      duration: "16 min",
    },
    {
      id: "his-f5",
      title: "How Democracy Was Invented",
      description: "Athens, 508 BCE — citizens voting on laws for the first time. What they got right, and very wrong.",
      ageTier: "9-12",
      itemType: "Investigation",
      thumbGradient: "linear-gradient(135deg, #1e1b4b 0%, #d97706 100%)",
      duration: "18 min",
    },
  ],
  projects: [
    {
      id: "his-p1",
      title: "Build a Catapult",
      description: "A working medieval trebuchet from craft sticks and a spoon — then test siege physics with marshmallows.",
      ageTier: "3-5",
      itemType: "Project",
      thumbGradient: "linear-gradient(135deg, #7c2d12 0%, #f97316 100%)",
      duration: "1 hr",
      difficulty: "Easy",
      buildTime: "1 hour",
    },
    {
      id: "his-p2",
      title: "Illuminated Manuscript Page",
      description: "Create a page in the style of medieval monks — calligraphy, gold borders, illustrated margins.",
      ageTier: "6-8",
      itemType: "Project",
      thumbGradient: "linear-gradient(135deg, #292524 0%, #fde68a 100%)",
      duration: "2 hrs",
      difficulty: "Intermediate",
      buildTime: "2 hours",
    },
    {
      id: "his-p3",
      title: "Map an Ancient Trade Route",
      description: "Research a historical trade route and map it — goods traded, peoples met, ideas exchanged.",
      ageTier: "9-12",
      itemType: "Project",
      thumbGradient: "linear-gradient(135deg, #1c1917 0%, #d97706 100%)",
      duration: "2 hrs",
      difficulty: "Advanced",
      buildTime: "2–3 hours",
    },
  ],
  trails: [
    {
      id: "his-t1",
      title: "Ancient World to Modern Life",
      description: "Trace the direct line from ancient civilizations to the systems we rely on every single day.",
      steps: ["Ancient Egypt", "Greece", "Rome", "Renaissance", "Enlightenment", "Now"],
      ageTier: "6-8",
      itemCount: 6,
      thumbGradient: "linear-gradient(135deg, #292524 0%, #fbbf24 100%)",
    },
    {
      id: "his-t2",
      title: "Inventors That Changed History",
      description: "A curated journey through the breakthroughs that permanently altered human civilization.",
      steps: ["Writing", "Printing Press", "Steam Engine", "Electricity", "Internet"],
      ageTier: "All Ages",
      itemCount: 5,
      thumbGradient: "linear-gradient(135deg, #1c1917 0%, #d97706 100%)",
    },
  ],
};

// ─── 7. Maker Projects ────────────────────────────────────────────────────────

const MAKER: Subject = {
  id: "maker-projects",
  slug: "maker-projects",
  title: "Maker Projects",
  subhead: "Garage builds, hands-on projects, repair skills, crafts, tools, and invention challenges.",
  heroSubhead: "The best learning happens when you make something real. Whether it's paper, wood, code, or electronics — the maker mindset is the same: build, break, learn, repeat.",
  icon: "🛠️",
  accentColor: "#ec4899",
  thumbGradient: "linear-gradient(135deg, #500724 0%, #be185d 60%, #f472b6 100%)",
  subtopics: [
    { id: "weekend-builds", label: "Weekend Builds" },
    { id: "tools", label: "Tools" },
    { id: "repair", label: "Repair" },
    { id: "diy", label: "DIY" },
    { id: "projects", label: "Projects" },
    { id: "challenges", label: "Challenges" },
  ],
  featuredItems: [
    {
      id: "mkr-f1",
      title: "Paper Engineering: Beyond Origami",
      description: "Kirigami, pop-up mechanisms, tensegrity — the surprising structures you can make with a single sheet.",
      ageTier: "K-2",
      itemType: "Workshop",
      thumbGradient: "linear-gradient(135deg, #0c4a6e 0%, #f472b6 100%)",
      duration: "20 min",
    },
    {
      id: "mkr-f2",
      title: "Cardboard Automata",
      description: "Cams, cranks, and linkages — make a creature that waves its arms with a turn of a knob. No power required.",
      ageTier: "6-8",
      itemType: "Workshop",
      thumbGradient: "linear-gradient(135deg, #3b0764 0%, #ec4899 100%)",
      duration: "45 min",
      episodes: 3,
    },
    {
      id: "mkr-f3",
      title: "Fix It Before You Bin It",
      description: "Repair over replacement — how to fix a zipper, resole a shoe, patch denim, and solder a wire.",
      ageTier: "All Ages",
      itemType: "Investigation",
      thumbGradient: "linear-gradient(135deg, #292524 0%, #f472b6 100%)",
      duration: "22 min",
    },
    {
      id: "mkr-f4",
      title: "3D Printed Gadgets That Actually Work",
      description: "Five practical objects — a cable organizer, a plant propagation station, a door latch — designed from scratch.",
      ageTier: "9-12",
      itemType: "Mini-Doc",
      thumbGradient: "linear-gradient(135deg, #0f172a 0%, #ec4899 100%)",
      duration: "18 min",
    },
    {
      id: "mkr-f5",
      title: "Sewing 101: Make a Tote Bag",
      description: "Threading, stitching, finishing seams — complete a real sewn project. Skills that last a lifetime.",
      ageTier: "All Ages",
      itemType: "Workshop",
      thumbGradient: "linear-gradient(135deg, #831843 0%, #f9a8d4 100%)",
      duration: "55 min",
    },
  ],
  projects: [
    {
      id: "mkr-p1",
      title: "Paper Bridge Challenge",
      description: "One sheet of paper, two stacks of books as pillars — design a bridge that holds the most pennies.",
      ageTier: "K-2",
      itemType: "Project",
      thumbGradient: "linear-gradient(135deg, #0c4a6e 0%, #f9a8d4 100%)",
      duration: "30 min",
      difficulty: "Easy",
      buildTime: "30 min",
    },
    {
      id: "mkr-p2",
      title: "DIY Solar Oven",
      description: "Cook a s'more using a pizza box, aluminum foil, and direct sunlight. Measure temperatures throughout.",
      ageTier: "3-5",
      itemType: "Project",
      thumbGradient: "linear-gradient(135deg, #713f12 0%, #fbbf24 100%)",
      duration: "1.5 hrs",
      difficulty: "Intermediate",
      buildTime: "1.5 hours",
    },
    {
      id: "mkr-p3",
      title: "Cardboard Marble Run",
      description: "Design a marble run with at least 4 different mechanisms: drop, loop, ramp, gate, and funnel.",
      ageTier: "6-8",
      itemType: "Project",
      thumbGradient: "linear-gradient(135deg, #500724 0%, #ec4899 100%)",
      duration: "3 hrs",
      difficulty: "Advanced",
      buildTime: "3 hours",
    },
  ],
  trails: [
    {
      id: "mkr-t1",
      title: "Beginner Maker Path",
      description: "The first four skills every maker needs — start simple, build confidence, progress to real builds.",
      steps: ["Safety First", "Hand Tools", "Measuring", "First Build"],
      ageTier: "K-2",
      itemCount: 4,
      thumbGradient: "linear-gradient(135deg, #0c4a6e 0%, #f472b6 100%)",
    },
    {
      id: "mkr-t2",
      title: "Advanced Fabrication Trail",
      description: "Move from manual builds to digital fabrication — laser cutting, CNC, and 3D printing.",
      steps: ["CAD Design", "3D Printing", "Laser Cutting", "CNC", "Assembly"],
      ageTier: "9-12",
      itemCount: 5,
      thumbGradient: "linear-gradient(135deg, #0f172a 0%, #ec4899 100%)",
    },
  ],
};

// ─── 8. Money & Business ──────────────────────────────────────────────────────

const MONEY: Subject = {
  id: "money-business",
  slug: "money-business",
  title: "Money & Business",
  subhead: "Entrepreneurship, markets, trade, invention, negotiation, and understanding value.",
  heroSubhead: "Money is just a tool for exchanging value. Understanding how it works — and how businesses create it — is one of the most practical things you can learn.",
  icon: "💡",
  accentColor: "#0ea5e9",
  thumbGradient: "linear-gradient(135deg, #0c4a6e 0%, #0ea5e9 60%, #22d3ee 100%)",
  subtopics: [
    { id: "entrepreneurship", label: "Entrepreneurship" },
    { id: "trade", label: "Trade" },
    { id: "saving", label: "Saving" },
    { id: "investing", label: "Investing" },
    { id: "inventions", label: "Inventions" },
    { id: "economics", label: "Economics" },
  ],
  featuredItems: [
    {
      id: "mon-f1",
      title: "What Gives Money Its Value?",
      description: "From cowrie shells to Bitcoin — what makes something money and why does everyone agree it works?",
      ageTier: "3-5",
      itemType: "Investigation",
      thumbGradient: "linear-gradient(135deg, #713f12 0%, #22d3ee 100%)",
      duration: "10 min",
    },
    {
      id: "mon-f2",
      title: "The Magic of Compound Interest",
      description: "Start with $100 at age 15. Watch where it goes by 25, 45, and 65. The math will change how you think.",
      ageTier: "6-8",
      itemType: "Interactive",
      thumbGradient: "linear-gradient(135deg, #052e16 0%, #0ea5e9 100%)",
      duration: "15 min",
    },
    {
      id: "mon-f3",
      title: "Teen Entrepreneurs Who Built Real Businesses",
      description: "Five teenagers who started companies from scratch — what worked, what failed, and what they wished they knew.",
      ageTier: "All Ages",
      itemType: "Mini-Doc",
      thumbGradient: "linear-gradient(135deg, #1e1b4b 0%, #22d3ee 100%)",
      duration: "22 min",
    },
    {
      id: "mon-f4",
      title: "Supply, Demand, and the Invisible Hand",
      description: "Why prices rise and fall — and how millions of people coordinate without anyone being in charge.",
      ageTier: "9-12",
      itemType: "Investigation",
      thumbGradient: "linear-gradient(135deg, #0c4a6e 0%, #f59e0b 100%)",
      duration: "18 min",
    },
    {
      id: "mon-f5",
      title: "How Stocks Actually Work",
      description: "Ownership, dividends, P/E ratios, and why the stock market goes up and down — clearly explained.",
      ageTier: "9-12",
      itemType: "Interactive",
      thumbGradient: "linear-gradient(135deg, #1e3a5f 0%, #0ea5e9 100%)",
      duration: "20 min",
    },
  ],
  projects: [
    {
      id: "mon-p1",
      title: "Lemonade Stand Business Plan",
      description: "Cost of goods, pricing, profit margin, and a simple marketing plan — a real business from scratch.",
      ageTier: "3-5",
      itemType: "Project",
      thumbGradient: "linear-gradient(135deg, #713f12 0%, #fbbf24 100%)",
      duration: "1 hr",
      difficulty: "Easy",
      buildTime: "1 hour",
    },
    {
      id: "mon-p2",
      title: "Mock Stock Portfolio",
      description: "Choose $10,000 in virtual stocks, track them for 30 days, and write a retrospective on your decisions.",
      ageTier: "6-8",
      itemType: "Project",
      thumbGradient: "linear-gradient(135deg, #0c4a6e 0%, #22d3ee 100%)",
      duration: "Ongoing",
      difficulty: "Intermediate",
      buildTime: "Setup 30 min + 30 days tracking",
    },
    {
      id: "mon-p3",
      title: "Pitch a Business Idea",
      description: "Research a problem, design a solution, and deliver a 5-minute pitch with slides and financial projections.",
      ageTier: "9-12",
      itemType: "Project",
      thumbGradient: "linear-gradient(135deg, #1e1b4b 0%, #0ea5e9 100%)",
      duration: "2 hrs",
      difficulty: "Advanced",
      buildTime: "2–3 hours",
    },
  ],
  trails: [
    {
      id: "mon-t1",
      title: "Earning to Investing",
      description: "The full personal finance journey — from your first dollar earned to your first investment made.",
      steps: ["Earning", "Budgeting", "Saving", "Compound Interest", "Investing"],
      ageTier: "6-8",
      itemCount: 5,
      thumbGradient: "linear-gradient(135deg, #052e16 0%, #0ea5e9 100%)",
    },
    {
      id: "mon-t2",
      title: "Startup Foundations",
      description: "From idea to pitch — the core steps every entrepreneur goes through when building a real business.",
      steps: ["Problem", "Solution", "Market", "Business Model", "Pitch"],
      ageTier: "9-12",
      itemCount: 5,
      thumbGradient: "linear-gradient(135deg, #1e1b4b 0%, #22d3ee 100%)",
    },
  ],
};

// ─── 9. Human Skills ──────────────────────────────────────────────────────────

const HUMAN_SKILLS: Subject = {
  id: "human-skills",
  slug: "human-skills",
  title: "Human Skills",
  subhead: "Communication, leadership, focus, confidence, memory, discipline, and human growth.",
  heroSubhead: "The skills that matter most are rarely taught in school. How to focus, listen deeply, lead with integrity, handle conflict, and keep growing — these are learnable.",
  icon: "🧠",
  accentColor: "#a855f7",
  thumbGradient: "linear-gradient(135deg, #2e1065 0%, #7c3aed 60%, #c084fc 100%)",
  subtopics: [
    { id: "leadership", label: "Leadership" },
    { id: "communication", label: "Communication" },
    { id: "memory", label: "Memory" },
    { id: "discipline", label: "Discipline" },
    { id: "focus", label: "Focus" },
    { id: "fitness", label: "Fitness" },
  ],
  featuredItems: [
    {
      id: "hsk-f1",
      title: "The Science of Deep Focus",
      description: "Flow states, attention spans, and the one habit that makes high performers different from everyone else.",
      ageTier: "6-8",
      itemType: "Investigation",
      thumbGradient: "linear-gradient(135deg, #2e1065 0%, #818cf8 100%)",
      duration: "16 min",
    },
    {
      id: "hsk-f2",
      title: "How Memory Actually Works",
      description: "The hippocampus, spaced repetition, and sleep — the neuroscience of remembering and forgetting.",
      ageTier: "All Ages",
      itemType: "Mini-Doc",
      thumbGradient: "linear-gradient(135deg, #1e1b4b 0%, #a855f7 100%)",
      duration: "18 min",
    },
    {
      id: "hsk-f3",
      title: "Conflict Resolution That Actually Works",
      description: "Interest-based negotiation, de-escalation, and the difference between positions and underlying needs.",
      ageTier: "9-12",
      itemType: "Interactive",
      thumbGradient: "linear-gradient(135deg, #450a0a 0%, #a855f7 100%)",
      duration: "22 min",
    },
    {
      id: "hsk-f4",
      title: "Build a Morning Routine That Sticks",
      description: "Habit stacking, environment design, and why most routines fail by week two — and how to prevent it.",
      ageTier: "All Ages",
      itemType: "Workshop",
      thumbGradient: "linear-gradient(135deg, #713f12 0%, #c084fc 100%)",
      duration: "15 min",
    },
    {
      id: "hsk-f5",
      title: "Public Speaking Without Fear",
      description: "Preparation, breath control, eye contact, and the one reframe that changes everything about speaking in public.",
      ageTier: "9-12",
      itemType: "Workshop",
      thumbGradient: "linear-gradient(135deg, #0c4a6e 0%, #a855f7 100%)",
      duration: "30 min",
    },
  ],
  projects: [
    {
      id: "hsk-p1",
      title: "30-Day Focus Challenge",
      description: "One focused hour per day on one chosen skill — track progress, notice resistance, report back.",
      ageTier: "All Ages",
      itemType: "Project",
      thumbGradient: "linear-gradient(135deg, #2e1065 0%, #c084fc 100%)",
      duration: "30 days",
      difficulty: "Easy",
      buildTime: "1 hour/day × 30 days",
    },
    {
      id: "hsk-p2",
      title: "Personal Budget Challenge",
      description: "Track every dollar you spend for two weeks, categorize it, and identify one real change you can make.",
      ageTier: "6-8",
      itemType: "Project",
      thumbGradient: "linear-gradient(135deg, #052e16 0%, #a855f7 100%)",
      duration: "2 hrs",
      difficulty: "Intermediate",
      buildTime: "Setup 1 hour + 2 weeks tracking",
    },
    {
      id: "hsk-p3",
      title: "Write and Deliver a 5-Minute Speech",
      description: "Choose a topic you care about, research it, write the speech, practice it, and deliver it on camera.",
      ageTier: "9-12",
      itemType: "Project",
      thumbGradient: "linear-gradient(135deg, #1e1b4b 0%, #f472b6 100%)",
      duration: "2 hrs",
      difficulty: "Advanced",
      buildTime: "2–3 hours",
    },
  ],
  trails: [
    {
      id: "hsk-t1",
      title: "Communication Mastery",
      description: "Listening is where it starts. End with the ability to lead a room without raising your voice.",
      steps: ["Deep Listening", "Clarity", "Persuasion", "Conflict", "Leadership"],
      ageTier: "9-12",
      itemCount: 5,
      thumbGradient: "linear-gradient(135deg, #2e1065 0%, #818cf8 100%)",
    },
    {
      id: "hsk-t2",
      title: "Mind & Body Path",
      description: "The research is clear: physical health and mental clarity are inseparable. Build both together.",
      steps: ["Sleep", "Nutrition", "Movement", "Focus", "Recovery", "Growth"],
      ageTier: "All Ages",
      itemCount: 6,
      thumbGradient: "linear-gradient(135deg, #052e16 0%, #c084fc 100%)",
    },
  ],
};

// ─── Exports ──────────────────────────────────────────────────────────────────

export const SUBJECTS: Subject[] = [
  SCIENCE,
  MATH,
  CODE,
  ENGINEERING,
  NATURE,
  HISTORY,
  MAKER,
  MONEY,
  HUMAN_SKILLS,
];

export function getSubjectBySlug(slug: string): Subject | undefined {
  return SUBJECTS.find((s) => s.slug === slug);
}

/** Pull a handful of trails from across subjects for the home page featured section. */
export const FEATURED_HOME_TRAILS = [
  SCIENCE.trails[1],    // Space Exploration Path
  CODE.trails[0],       // Logic to Programs
  HISTORY.trails[1],    // Inventors That Changed History
];
